from sqlalchemy import Column, Float, Integer, String
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class XdrData(Base):
    __tablename__ = 'xdr_data'

    bearer_id = Column(Float, primary_key=True)
    start = Column(String)
    start_ms = Column(Float)
    end = Column(String)
    end_ms = Column(Float)
    duration_ms = Column(Float)
    imsi = Column(Float)
    msisdn_number = Column(Float)
    imei = Column(Float)
    last_location_name = Column(String)
    avg_rtt_dl_ms = Column(Float)
    avg_rtt_ul_ms = Column(Float)
    avg_bearer_tp_dl_kbps = Column(Float)
    avg_bearer_tp_ul_kbps = Column(Float)
    tcp_dl_retrans_vol_bytes = Column(Float)
    tcp_ul_retrans_vol_bytes = Column(Float)
    dl_tp_lt_50_kbps = Column(Float)
    dl_tp_50_kbps_lt_250_kbps = Column(Float)
    dl_tp_250_kbps_lt_1_mbps = Column(Float)
    dl_tp_gt_1_mbps = Column(Float)
    ul_tp_lt_10_kbps = Column(Float)
    ul_tp_10_kbps_lt_50_kbps = Column(Float)
    ul_tp_50_kbps_lt_300_kbps = Column(Float)
    ul_tp_gt_300_kbps = Column(Float)
    http_dl_bytes = Column(Float)
    http_ul_bytes = Column(Float)
    activity_duration_dl_ms = Column(Float)
    activity_duration_ul_ms = Column(Float)
    duration_ms_1 = Column(Float)
    handset_manufacturer = Column(String)
    handset_type = Column(String)
    nb_of_sec_with_125000b_lt_vol_dl = Column(Float)
    nb_of_sec_with_1250b_lt_vol_ul_lt_6250b = Column(Float)
    nb_of_sec_with_31250b_lt_vol_dl_lt_125000b = Column(Float)
    nb_of_sec_with_37500b_lt_vol_ul = Column(Float)
    nb_of_sec_with_6250b_lt_vol_dl_lt_31250b = Column(Float)
    nb_of_sec_with_6250b_lt_vol_ul_lt_37500b = Column(Float)
    nb_of_sec_with_vol_dl_lt_6250b = Column(Float)
    nb_of_sec_with_vol_ul_lt_1250b = Column(Float)
    social_media_dl_bytes = Column(Float)
    social_media_ul_bytes = Column(Float)
    google_dl_bytes = Column(Float)
    google_ul_bytes = Column(Float)
    email_dl_bytes = Column(Float)
    email_ul_bytes = Column(Float)
    youtube_dl_bytes = Column(Float)
    youtube_ul_bytes = Column(Float)
    netflix_dl_bytes = Column(Float)
    netflix_ul_bytes = Column(Float)
    gaming_dl_bytes = Column(Float)
    gaming_ul_bytes = Column(Float)
    other_dl_bytes = Column(Float)
    other_ul_bytes = Column(Float)
    total_ul_bytes = Column(Float)
    total_dl_bytes = Column(Float)